language: node_js
node_js:
- 8
- 7
- 6
- 5
script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test-no-cache
- npm run build
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: tzJLVyWek8siZMn+UgIgTETt6KdkhSjzaIxD9Q+Xz8Ay1qIRzT8pJHYIYxNsRAy4eJyzbDCeFUuTRh7CCKj4cI2d6On2zfIgKYxCB6bVOTLxakj09Qv6bVKFSAz9Z67xoUFEiQ0slTKrxHC9KOGQ8UavfKVJlCkypnAHgXc8pBxYlOMRf/61MXFlmG+y3qWoa6rqrzlaGMFqvdQCjzmzB9BEZWZyF0JZdAmua23WlsGGNLDn4ctkkBSI1sgBtsWDyqmPIfJgNp+PZnPaabU36+21FChAnBm7URg0W9IkBGZ7DH1caOaE8uewAp9rWv+pX0ZljZJOkUzTjxv6JNAR4EG7TO12Ulp/Qn2FKjF5c35yPpplUMruf6VfpghqGmDbLM3Su5dHTGnoucOpWD4d1zO26wxLv04SPk5Ye/n/lsP+QIQ4Gv0vO5n4HCWucyEWbzVvwk8nWyXVDe2R7jnUL8AmVgReyNoLcbrqXLpTkuyOHjnZcVF9A1idR5aTwrILYB94q+yVpMsOZVib05Dmf5UBsRNvAEzLpMuLFJNrZC0XhxUOSLks7xX632jlyFPi5/ZHUCM57j4cRn0pha7AyWgx1Pc7SMoWyYly3wjwmKoRxK34r8tureR2cgiVUSO/7Epm96zQKHgvUhbfRofWoL1+knyzImU9zfdoV25fVOk=
  app: avanced-react-bitcoin-wallet
  on:
    repo: blockchainkatas/avanced-react-bitcoin-wallet
  run: "npm run start:prod"
